//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.02 at 01:16:15 PM CEST 
//


package com.tcs.dg.jaxb.produces;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mfh">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ffv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="st" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cbt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="md" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="neid">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="neun" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nedn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nesw" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="mi" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="mts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="gp" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="mt" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="mv" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="moid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="r" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                       &lt;element name="sf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mff">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mfh",
    "md",
    "mff"
})
@XmlRootElement(name = "mdc")
public class Mdc{

    @XmlElement(required = true)
    protected Mdc.Mfh mfh;
    @XmlElement(required = true)
    protected List<Mdc.Md> md;
    @XmlElement(required = true)
    protected Mdc.Mff mff;
         
    

    
	     
    
    /**
     * Gets the value of the mfh property.
     * 
     * @return
     *     possible object is
     *     {@link Mdc.Mfh }
     *     
     */
    public Mdc.Mfh getMfh() {
        return mfh;
    }

    /**
     * Sets the value of the mfh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mdc.Mfh }
     *     
     */
    public void setMfh(Mdc.Mfh value) {
        this.mfh = value;
    }

    /**
     * Gets the value of the md property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the md property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mdc.Md }
     * 
     * 
     */
    public List<Mdc.Md> getMd() {
        if (md == null) {
            md = new ArrayList<Mdc.Md>();
        }
        return this.md;
    }

    /**
     * Gets the value of the mff property.
     * 
     * @return
     *     possible object is
     *     {@link Mdc.Mff }
     *     
     */
    public Mdc.Mff getMff() {
        return mff;
    }

    /**
     * Sets the value of the mff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mdc.Mff }
     *     
     */
    public void setMff(Mdc.Mff value) {
        this.mff = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="neid">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="neun" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nedn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nesw" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="mi" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="mts" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="gp" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="mt" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="mv" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="moid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="r" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                             &lt;element name="sf" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "neid",
        "mi"
    })
    public static class Md {

        @XmlElement(required = true)
        protected Mdc.Md.Neid neid;
        @XmlElement(required = true)
        protected List<Mdc.Md.Mi> mi;

        /**
         * Gets the value of the neid property.
         * 
         * @return
         *     possible object is
         *     {@link Mdc.Md.Neid }
         *     
         */
        public Mdc.Md.Neid getNeid() {
            return neid;
        }

        /**
         * Sets the value of the neid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mdc.Md.Neid }
         *     
         */
        public void setNeid(Mdc.Md.Neid value) {
            this.neid = value;
        }

        /**
         * Gets the value of the mi property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mi property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMi().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mdc.Md.Mi }
         * 
         * 
         */
        public List<Mdc.Md.Mi> getMi() {
            if (mi == null) {
                mi = new ArrayList<Mdc.Md.Mi>();
            }
            return this.mi;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="mts" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="gp" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="mt" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="mv" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="moid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="r" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                   &lt;element name="sf" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mts",
            "gp",
            "mt",
            "mv"
        })
        public static class Mi {

            @XmlElement(required = true)
            protected String mts;
            protected int gp;
            @XmlElement(required = true)
            protected List<String> mt;
            @XmlElement(required = true)
            protected List<Mdc.Md.Mi.Mv> mv;

            /**
             * Gets the value of the mts property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMts() {
                return mts;
            }

            /**
             * Sets the value of the mts property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMts(String value) {
                this.mts = value;
            }

            /**
             * Gets the value of the gp property.
             * 
             */
            public int getGp() {
                return gp;
            }

            /**
             * Sets the value of the gp property.
             * 
             */
            public void setGp(int value) {
                this.gp = value;
            }

            /**
             * Gets the value of the mt property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the mt property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMt().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getMt() {
                if (mt == null) {
                    mt = new ArrayList<String>();
                }
                return this.mt;
            }

            /**
             * Gets the value of the mv property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the mv property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMv().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Mdc.Md.Mi.Mv }
             * 
             * 
             */
            public List<Mdc.Md.Mi.Mv> getMv() {
                if (mv == null) {
                    mv = new ArrayList<Mdc.Md.Mi.Mv>();
                }
                return this.mv;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="moid" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="r" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *         &lt;element name="sf" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "moid",
                "r",
                "sf"
            })
            public static class Mv {

                @XmlElement(required = true)
                protected String moid;
                @XmlElement(required = true)
                protected List<String> r;
                @XmlElement(required = true)
                protected String sf;

                /**
                 * Gets the value of the moid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMoid() {
                    return moid;
                }

                /**
                 * Sets the value of the moid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMoid(String value) {
                    this.moid = value;
                }

                /**
                 * Gets the value of the r property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the r property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getR().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getR() {
                    if (r == null) {
                        r = new ArrayList<String>();
                    }
                    return this.r;
                }

                /**
                 * Gets the value of the sf property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSf() {
                    return sf;
                }

                /**
                 * Sets the value of the sf property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSf(String value) {
                    this.sf = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="neun" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nedn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nesw" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "neun",
            "nedn",
            "nesw"
        })
        public static class Neid {

            @XmlElement(required = true)
            protected String neun;
            @XmlElement(required = true)
            protected String nedn;
            @XmlElement(required = true)
            protected String nesw;

            /**
             * Gets the value of the neun property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNeun() {
                return neun;
            }

            /**
             * Sets the value of the neun property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNeun(String value) {
                this.neun = value;
            }

            /**
             * Gets the value of the nedn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNedn() {
                return nedn;
            }

            /**
             * Sets the value of the nedn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNedn(String value) {
                this.nedn = value;
            }

            /**
             * Gets the value of the nesw property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNesw() {
                return nesw;
            }

            /**
             * Sets the value of the nesw property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNesw(String value) {
                this.nesw = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ts" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ts"
    })
    public static class Mff {

        @XmlElement(required = true)
        protected String ts;

        /**
         * Gets the value of the ts property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTs() {
            return ts;
        }

        /**
         * Sets the value of the ts property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTs(String value) {
            this.ts = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ffv" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="st" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="vn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cbt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ffv",
        "sn",
        "st",
        "vn",
        "cbt"
    })
    public static class Mfh {

        @XmlElement(required = true)
        protected String ffv;
        @XmlElement(required = true)
        protected String sn;
        @XmlElement(required = true)
        protected String st;
        @XmlElement(required = true)
        protected String vn;
        @XmlElement(required = true)
        protected String cbt;

        /**
         * Gets the value of the ffv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFfv() {
            return ffv;
        }

        /**
         * Sets the value of the ffv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFfv(String value) {
            this.ffv = value;
        }

        /**
         * Gets the value of the sn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSn() {
            return sn;
        }

        /**
         * Sets the value of the sn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSn(String value) {
            this.sn = value;
        }

        /**
         * Gets the value of the st property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSt() {
            return st;
        }

        /**
         * Sets the value of the st property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSt(String value) {
            this.st = value;
        }

        /**
         * Gets the value of the vn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVn() {
            return vn;
        }

        /**
         * Sets the value of the vn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVn(String value) {
            this.vn = value;
        }

        /**
         * Gets the value of the cbt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCbt() {
            return cbt;
        }

        /**
         * Sets the value of the cbt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCbt(String value) {
            this.cbt = value;
        }

    }

}
