//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.02 at 01:16:15 PM CEST 
//


package com.tcs.dg.jaxb.produces;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tcs.dg.jaxb.produces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tcs.dg.jaxb.produces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mdc }
     * 
     */
    public Mdc createMdc() {
        return new Mdc();
    }

    /**
     * Create an instance of {@link Mdc.Md }
     * 
     */
    public Mdc.Md createMdcMd() {
        return new Mdc.Md();
    }

    /**
     * Create an instance of {@link Mdc.Md.Mi }
     * 
     */
    public Mdc.Md.Mi createMdcMdMi() {
        return new Mdc.Md.Mi();
    }

    /**
     * Create an instance of {@link Mdc.Mfh }
     * 
     */
    public Mdc.Mfh createMdcMfh() {
        return new Mdc.Mfh();
    }

    /**
     * Create an instance of {@link Mdc.Mff }
     * 
     */
    public Mdc.Mff createMdcMff() {
        return new Mdc.Mff();
    }

    /**
     * Create an instance of {@link Mdc.Md.Neid }
     * 
     */
    public Mdc.Md.Neid createMdcMdNeid() {
        return new Mdc.Md.Neid();
    }

    /**
     * Create an instance of {@link Mdc.Md.Mi.Mv }
     * 
     */
    public Mdc.Md.Mi.Mv createMdcMdMiMv() {
        return new Mdc.Md.Mi.Mv();
    }

}
