//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.05 at 11:39:39 AM CEST 
//


package com.tcs.dg.jaxb.userconfig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tcs.dg.jaxb.userconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tcs.dg.jaxb.userconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserInputSpecification }
     * 
     */
    public UserInputSpecification createUserInputSpecification() {
        return new UserInputSpecification();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources }
     * 
     */
    public UserInputSpecification.DataSources createUserInputSpecificationDataSources() {
        return new UserInputSpecification.DataSources();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.Element }
     * 
     */
    public UserInputSpecification.DataSources.Element createUserInputSpecificationDataSourcesElement() {
        return new UserInputSpecification.DataSources.Element();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.Element.Value }
     * 
     */
    public UserInputSpecification.DataSources.Element.Value createUserInputSpecificationDataSourcesElementValue() {
        return new UserInputSpecification.DataSources.Element.Value();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.DataSource }
     * 
     */
    public UserInputSpecification.DataSources.DataSource createUserInputSpecificationDataSourcesDataSource() {
        return new UserInputSpecification.DataSources.DataSource();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions }
     * 
     */
    public UserInputSpecification.DataSources.DataSource.EnrichmentOptions createUserInputSpecificationDataSourcesDataSourceEnrichmentOptions() {
        return new UserInputSpecification.DataSources.DataSource.EnrichmentOptions();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment }
     * 
     */
    public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment createUserInputSpecificationDataSourcesDataSourceEnrichmentOptionsGenericEnrichment() {
        return new UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element }
     * 
     */
    public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element createUserInputSpecificationDataSourcesDataSourceEnrichmentOptionsGenericEnrichmentElement() {
        return new UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value }
     * 
     */
    public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value createUserInputSpecificationDataSourcesDataSourceEnrichmentOptionsGenericEnrichmentElementValue() {
        return new UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.Element.Value.List }
     * 
     */
    public UserInputSpecification.DataSources.Element.Value.List createUserInputSpecificationDataSourcesElementValueList() {
        return new UserInputSpecification.DataSources.Element.Value.List();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.DataSource.GeneralInfo }
     * 
     */
    public UserInputSpecification.DataSources.DataSource.GeneralInfo createUserInputSpecificationDataSourcesDataSourceGeneralInfo() {
        return new UserInputSpecification.DataSources.DataSource.GeneralInfo();
    }

    /**
     * Create an instance of {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment }
     * 
     */
    public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment createUserInputSpecificationDataSourcesDataSourceEnrichmentOptionsGenericEnrichmentElementValueIncrement() {
        return new UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment();
    }

}
