//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.05 at 11:39:39 AM CEST 
//


package com.tcs.dg.jaxb.userconfig;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeletionFactor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DataSources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DataSource" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="GeneralInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="InputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OutputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="IntermediateLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Repetition" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="NumberOfNode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ROPTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="FileType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="EnrichmentOptions">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="GenericEnrichment">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Element">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="Value">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="Increment">
 *                                                                       &lt;complexType>
 *                                                                         &lt;complexContent>
 *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                             &lt;sequence>
 *                                                                               &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                                               &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                                             &lt;/sequence>
 *                                                                           &lt;/restriction>
 *                                                                         &lt;/complexContent>
 *                                                                       &lt;/complexType>
 *                                                                     &lt;/element>
 *                                                                   &lt;/sequence>
 *                                                                   &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Element" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Value">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="List">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ListElement" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deletionFactor",
    "dataSources"
})
@XmlRootElement(name = "UserInputSpecification")
public class UserInputSpecification {

    @XmlElement(name = "DeletionFactor")
    protected int deletionFactor;
    @XmlElement(name = "DataSources", required = true)
    protected UserInputSpecification.DataSources dataSources;

    /**
     * Gets the value of the deletionFactor property.
     * 
     */
    public int getDeletionFactor() {
        return deletionFactor;
    }

    /**
     * Sets the value of the deletionFactor property.
     * 
     */
    public void setDeletionFactor(int value) {
        this.deletionFactor = value;
    }

    /**
     * Gets the value of the dataSources property.
     * 
     * @return
     *     possible object is
     *     {@link UserInputSpecification.DataSources }
     *     
     */
    public UserInputSpecification.DataSources getDataSources() {
        return dataSources;
    }

    /**
     * Sets the value of the dataSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInputSpecification.DataSources }
     *     
     */
    public void setDataSources(UserInputSpecification.DataSources value) {
        this.dataSources = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DataSource" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="GeneralInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="InputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="OutputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="IntermediateLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Repetition" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="NumberOfNode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ROPTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="FileType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="EnrichmentOptions">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="GenericEnrichment">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Element">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="Value">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="Increment">
     *                                                             &lt;complexType>
     *                                                               &lt;complexContent>
     *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                                   &lt;sequence>
     *                                                                     &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                                                     &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                                                   &lt;/sequence>
     *                                                                 &lt;/restriction>
     *                                                               &lt;/complexContent>
     *                                                             &lt;/complexType>
     *                                                           &lt;/element>
     *                                                         &lt;/sequence>
     *                                                         &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Element" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Value">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="List">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ListElement" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSource",
        "element"
    })
    public static class DataSources {

        @XmlElement(name = "DataSource", required = true)
        protected java.util.List<UserInputSpecification.DataSources.DataSource> dataSource;
        @XmlElement(name = "Element", required = true)
        protected java.util.List<UserInputSpecification.DataSources.Element> element;

        /**
         * Gets the value of the dataSource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataSource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataSource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserInputSpecification.DataSources.DataSource }
         * 
         * 
         */
        public java.util.List<UserInputSpecification.DataSources.DataSource> getDataSource() {
            if (dataSource == null) {
                dataSource = new ArrayList<UserInputSpecification.DataSources.DataSource>();
            }
            return this.dataSource;
        }

        /**
         * Gets the value of the element property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the element property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserInputSpecification.DataSources.Element }
         * 
         * 
         */
        public java.util.List<UserInputSpecification.DataSources.Element> getElement() {
            if (element == null) {
                element = new ArrayList<UserInputSpecification.DataSources.Element>();
            }
            return this.element;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="GeneralInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="InputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="OutputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="IntermediateLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Repetition" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="NumberOfNode" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ROPTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="FileType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="EnrichmentOptions">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="GenericEnrichment">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Element">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="Value">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="Increment">
         *                                                   &lt;complexType>
         *                                                     &lt;complexContent>
         *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                                         &lt;sequence>
         *                                                           &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                                                           &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                                                         &lt;/sequence>
         *                                                       &lt;/restriction>
         *                                                     &lt;/complexContent>
         *                                                   &lt;/complexType>
         *                                                 &lt;/element>
         *                                               &lt;/sequence>
         *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "generalInfo",
            "enrichmentOptions"
        })
        public static class DataSource {

            @XmlElement(name = "GeneralInfo", required = true)
            protected UserInputSpecification.DataSources.DataSource.GeneralInfo generalInfo;
            @XmlElement(name = "EnrichmentOptions", required = true)
            protected UserInputSpecification.DataSources.DataSource.EnrichmentOptions enrichmentOptions;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the generalInfo property.
             * 
             * @return
             *     possible object is
             *     {@link UserInputSpecification.DataSources.DataSource.GeneralInfo }
             *     
             */
            public UserInputSpecification.DataSources.DataSource.GeneralInfo getGeneralInfo() {
                return generalInfo;
            }

            /**
             * Sets the value of the generalInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link UserInputSpecification.DataSources.DataSource.GeneralInfo }
             *     
             */
            public void setGeneralInfo(UserInputSpecification.DataSources.DataSource.GeneralInfo value) {
                this.generalInfo = value;
            }

            /**
             * Gets the value of the enrichmentOptions property.
             * 
             * @return
             *     possible object is
             *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions }
             *     
             */
            public UserInputSpecification.DataSources.DataSource.EnrichmentOptions getEnrichmentOptions() {
                return enrichmentOptions;
            }

            /**
             * Sets the value of the enrichmentOptions property.
             * 
             * @param value
             *     allowed object is
             *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions }
             *     
             */
            public void setEnrichmentOptions(UserInputSpecification.DataSources.DataSource.EnrichmentOptions value) {
                this.enrichmentOptions = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="GenericEnrichment">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Element">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="Value">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="Increment">
             *                                         &lt;complexType>
             *                                           &lt;complexContent>
             *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                               &lt;sequence>
             *                                                 &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                                                 &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                                               &lt;/sequence>
             *                                             &lt;/restriction>
             *                                           &lt;/complexContent>
             *                                         &lt;/complexType>
             *                                       &lt;/element>
             *                                     &lt;/sequence>
             *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "genericEnrichment"
            })
            public static class EnrichmentOptions {

                @XmlElement(name = "GenericEnrichment", required = true)
                protected UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment genericEnrichment;

                /**
                 * Gets the value of the genericEnrichment property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment }
                 *     
                 */
                public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment getGenericEnrichment() {
                    return genericEnrichment;
                }

                /**
                 * Sets the value of the genericEnrichment property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment }
                 *     
                 */
                public void setGenericEnrichment(UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment value) {
                    this.genericEnrichment = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Element">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="Value">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="Increment">
                 *                               &lt;complexType>
                 *                                 &lt;complexContent>
                 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                                     &lt;sequence>
                 *                                       &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *                                       &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *                                     &lt;/sequence>
                 *                                   &lt;/restriction>
                 *                                 &lt;/complexContent>
                 *                               &lt;/complexType>
                 *                             &lt;/element>
                 *                           &lt;/sequence>
                 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "element"
                })
                public static class GenericEnrichment {

                    @XmlElement(name = "Element", required = true)
                    protected UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element element;

                    /**
                     * Gets the value of the element property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element }
                     *     
                     */
                    public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element getElement() {
                        return element;
                    }

                    /**
                     * Sets the value of the element property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element }
                     *     
                     */
                    public void setElement(UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element value) {
                        this.element = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="Value">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="Increment">
                     *                     &lt;complexType>
                     *                       &lt;complexContent>
                     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                           &lt;sequence>
                     *                             &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
                     *                             &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
                     *                           &lt;/sequence>
                     *                         &lt;/restriction>
                     *                       &lt;/complexContent>
                     *                     &lt;/complexType>
                     *                   &lt;/element>
                     *                 &lt;/sequence>
                     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "name",
                        "value"
                    })
                    public static class Element {

                        @XmlElement(name = "Name", required = true)
                        protected String name;
                        @XmlElement(name = "Value", required = true)
                        protected UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value value;

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value }
                         *     
                         */
                        public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value }
                         *     
                         */
                        public void setValue(UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value value) {
                            this.value = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="Increment">
                         *           &lt;complexType>
                         *             &lt;complexContent>
                         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *                 &lt;sequence>
                         *                   &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
                         *                   &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
                         *                 &lt;/sequence>
                         *               &lt;/restriction>
                         *             &lt;/complexContent>
                         *           &lt;/complexType>
                         *         &lt;/element>
                         *       &lt;/sequence>
                         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "increment"
                        })
                        public static class Value {

                            @XmlElement(name = "Increment", required = true)
                            protected UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment increment;
                            @XmlAttribute(name = "type")
                            protected String type;

                            /**
                             * Gets the value of the increment property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment }
                             *     
                             */
                            public UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment getIncrement() {
                                return increment;
                            }

                            /**
                             * Sets the value of the increment property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment }
                             *     
                             */
                            public void setIncrement(UserInputSpecification.DataSources.DataSource.EnrichmentOptions.GenericEnrichment.Element.Value.Increment value) {
                                this.increment = value;
                            }

                            /**
                             * Gets the value of the type property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getType() {
                                return type;
                            }

                            /**
                             * Sets the value of the type property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setType(String value) {
                                this.type = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType>
                             *   &lt;complexContent>
                             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                             *       &lt;sequence>
                             *         &lt;element name="BaseValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
                             *         &lt;element name="IncrementBy" type="{http://www.w3.org/2001/XMLSchema}int"/>
                             *       &lt;/sequence>
                             *     &lt;/restriction>
                             *   &lt;/complexContent>
                             * &lt;/complexType>
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "baseValue",
                                "incrementBy"
                            })
                            public static class Increment {

                                @XmlElement(name = "BaseValue")
                                protected int baseValue;
                                @XmlElement(name = "IncrementBy")
                                protected int incrementBy;

                                /**
                                 * Gets the value of the baseValue property.
                                 * 
                                 */
                                public int getBaseValue() {
                                    return baseValue;
                                }

                                /**
                                 * Sets the value of the baseValue property.
                                 * 
                                 */
                                public void setBaseValue(int value) {
                                    this.baseValue = value;
                                }

                                /**
                                 * Gets the value of the incrementBy property.
                                 * 
                                 */
                                public int getIncrementBy() {
                                    return incrementBy;
                                }

                                /**
                                 * Sets the value of the incrementBy property.
                                 * 
                                 */
                                public void setIncrementBy(int value) {
                                    this.incrementBy = value;
                                }

                            }

                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="InputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="OutputFileLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="IntermediateLoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Repetition" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="NumberOfNode" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ROPTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="FileType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "inputFileLocation",
                "outputFileLocation",
                "intermediateLoc",
                "repetition",
                "numberOfNode",
                "timeZone",
                "ropTime",
                "fileType"
            })
            public static class GeneralInfo {

                @XmlElement(name = "InputFileLocation", required = true)
                protected String inputFileLocation;
                @XmlElement(name = "OutputFileLocation", required = true)
                protected String outputFileLocation;
                @XmlElement(name = "IntermediateLoc", required = true)
                protected String intermediateLoc;
                @XmlElement(name = "Repetition")
                protected int repetition;
                @XmlElement(name = "NumberOfNode")
                protected int numberOfNode;
                @XmlElement(name = "TimeZone", required = true)
                protected String timeZone;
                @XmlElement(name = "ROPTime")
                protected int ropTime;
                @XmlElement(name = "FileType", required = true)
                protected String fileType;

                /**
                 * Gets the value of the inputFileLocation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInputFileLocation() {
                    return inputFileLocation;
                }

                /**
                 * Sets the value of the inputFileLocation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInputFileLocation(String value) {
                    this.inputFileLocation = value;
                }

                /**
                 * Gets the value of the outputFileLocation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOutputFileLocation() {
                    return outputFileLocation;
                }

                /**
                 * Sets the value of the outputFileLocation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOutputFileLocation(String value) {
                    this.outputFileLocation = value;
                }

                /**
                 * Gets the value of the intermediateLoc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIntermediateLoc() {
                    return intermediateLoc;
                }

                /**
                 * Sets the value of the intermediateLoc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIntermediateLoc(String value) {
                    this.intermediateLoc = value;
                }

                /**
                 * Gets the value of the repetition property.
                 * 
                 */
                public int getRepetition() {
                    return repetition;
                }

                /**
                 * Sets the value of the repetition property.
                 * 
                 */
                public void setRepetition(int value) {
                    this.repetition = value;
                }

                /**
                 * Gets the value of the numberOfNode property.
                 * 
                 */
                public int getNumberOfNode() {
                    return numberOfNode;
                }

                /**
                 * Sets the value of the numberOfNode property.
                 * 
                 */
                public void setNumberOfNode(int value) {
                    this.numberOfNode = value;
                }

                /**
                 * Gets the value of the timeZone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTimeZone() {
                    return timeZone;
                }

                /**
                 * Sets the value of the timeZone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTimeZone(String value) {
                    this.timeZone = value;
                }

                /**
                 * Gets the value of the ropTime property.
                 * 
                 */
                public int getROPTime() {
                    return ropTime;
                }

                /**
                 * Sets the value of the ropTime property.
                 * 
                 */
                public void setROPTime(int value) {
                    this.ropTime = value;
                }

                /**
                 * Gets the value of the fileType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFileType() {
                    return fileType;
                }

                /**
                 * Sets the value of the fileType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFileType(String value) {
                    this.fileType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Value">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="List">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ListElement" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "value"
        })
        public static class Element {

            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "Value", required = true)
            protected UserInputSpecification.DataSources.Element.Value value;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link UserInputSpecification.DataSources.Element.Value }
             *     
             */
            public UserInputSpecification.DataSources.Element.Value getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link UserInputSpecification.DataSources.Element.Value }
             *     
             */
            public void setValue(UserInputSpecification.DataSources.Element.Value value) {
                this.value = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="List">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ListElement" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "list"
            })
            public static class Value {

                @XmlElement(name = "List", required = true)
                protected UserInputSpecification.DataSources.Element.Value.List list;
                @XmlAttribute(name = "type")
                protected String type;

                /**
                 * Gets the value of the list property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link UserInputSpecification.DataSources.Element.Value.List }
                 *     
                 */
                public UserInputSpecification.DataSources.Element.Value.List getList() {
                    return list;
                }

                /**
                 * Sets the value of the list property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link UserInputSpecification.DataSources.Element.Value.List }
                 *     
                 */
                public void setList(UserInputSpecification.DataSources.Element.Value.List value) {
                    this.list = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ListElement" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "listElement"
                })
                public static class List {

                    @XmlElement(name = "ListElement", type = Integer.class)
                    protected java.util.List<Integer> listElement;
                    @XmlAttribute(name = "type")
                    protected String type;

                    /**
                     * Gets the value of the listElement property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the listElement property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getListElement().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Integer }
                     * 
                     * 
                     */
                    public java.util.List<Integer> getListElement() {
                        if (listElement == null) {
                            listElement = new ArrayList<Integer>();
                        }
                        return this.listElement;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                }

            }

        }

    }

}
